version: '3.2'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./backup:/backup
      - ./homework:/homework
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432