version: '3.2'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./data:/var/lib/postgresql
      - ./backup:/backup
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432