Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
   config.vm.provider "virtualbox" do |v|
   v.name = "vagrant_terraform"
       v.memory = 2024
       v.cpus = 2
   end
end